### ISSUE TITLE
socket.io removed "attach" and "listen" in version 4.4.1 so all examples fail 

### ISSUE THREAD

**Issue by hobson42** [open-easyrtc/open-easyrtc#91]
The example I am using contains the following two lines. 

```
var socketIo = require("socket.io");        // web socket external module
...
var socketServer = socketIo.listen(webServer, {"log level":1});    # this is line 40 
// var socketServer = socketIo.attach(webServer, {"log level":1});
```

This results in the error that socketio has no function listen.  Replacing listen with attach, results in a similar error. 

Note the docs for socket.io claim both still exist - see https://socket.io/docs/v4/server-api/#serverattachhttpserver-options
and https://socket.io/docs/v4/server-api/#serverattachhttpserver-options.

```
ian@dia:~$ pm2 list
┌─────┬───────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id  │ name      │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
└─────┴───────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
ian@dia:~$ pm2 start /var/www/open-easyrtc/server/server.js
[PM2] Starting /var/www/open-easyrtc/server/server.js in fork_mode (1 instance)
[PM2] Done.
┌─────┬───────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id  │ name      │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├─────┼───────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 0   │ server    │ default     │ 2.0.14  │ fork    │ 8460     │ 0s     │ 0    │ online    │ 0%       │ 31.4mb   │ ian      │ disabled │
└─────┴───────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
ian@dia:~$ pm2 list
┌─────┬───────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id  │ name      │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├─────┼───────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 0   │ server    │ default     │ 2.0.14  │ fork    │ 0        │ 0      │ 15   │ errored   │ 0%       │ 0b       │ ian      │ disabled │
└─────┴───────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
ian@dia:~$ cd ~/.pm2/logs
ian@dia:~/.pm2/logs$ ls
server-error.log  server-out.log
ian@dia:~/.pm2/logs$ tail -20 server-error.log 
    at Module._compile (node:internal/modules/cjs/loader:1119:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Module.load (node:internal/modules/cjs/loader:997:32)
    at Module._load (node:internal/modules/cjs/loader:838:12)
    at Object.<anonymous> (/usr/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
    at Module._compile (node:internal/modules/cjs/loader:1119:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Module.load (node:internal/modules/cjs/loader:997:32)
    at Module._load (node:internal/modules/cjs/loader:838:12)
TypeError: socketIo.attach is not a function
    at Object.<anonymous> (/var/www/open-easyrtc/server/server.js:40:29)
    at Module._compile (node:internal/modules/cjs/loader:1119:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Module.load (node:internal/modules/cjs/loader:997:32)
    at Module._load (node:internal/modules/cjs/loader:838:12)
    at Object.<anonymous> (/usr/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
    at Module._compile (node:internal/modules/cjs/loader:1119:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Module.load (node:internal/modules/cjs/loader:997:32)
    at Module._load (node:internal/modules/cjs/loader:838:12)
ian@dia:~/.pm2/logs$

**Comment by hthetiot** [comment]
For using Socket.io 4+ See PR https://github.com/open-easyrtc/open-easyrtc/pull/70
